import type { UserRole } from "./auth";

export type EmployeeRecord = {
  id: string;
  name: string | null;
  email: string | null;
  phone: string | null;
  profilePic: string | null;
  employeeId: string;
  company: string;
  role: UserRole;
  dateOfBirth: string | null;
  gender: string | null;
  accountStatus: string | null;
  department: string | null;
  designation: string | null;
  employmentType: string | null;
  workDaysPerWeek: number | null;
  workStartTime: string;
  workEndTime: string;
  joinDate: string | null;
  employmentStatus: string | null;
  basicSalary: string | null;
  salaryType: string | null;
  allowances: string | null;
  attendanceBonusThreshold: string | null;
  attendanceBonusRate: string | null;
  effectiveSalaryDate: string | null;
  address: string | null;
  city: string | null;
  country: string | null;
  emergencyContactName: string | null;
  emergencyContactPhone: string | null;
  manager: string | null;
  workLocation: string | null;
  lastLogin: string | null;
  createdAt: string;
  updatedAt: string;
};

export type EmployeeInput = {
  name: string;
  email: string;
  password?: string;
  phone?: string;
  profilePic?: string;
  dateOfBirth?: string;
  gender?: string;
  role: UserRole;
  accountStatus?: string;
  employeeId?: string;
  department?: string;
  designation?: string;
  employmentType?: string;
  workDaysPerWeek?: string;
  workStartTime?: string;
  workEndTime?: string;
  joinDate?: string;
  employmentStatus?: string;
  basicSalary?: string;
  salaryType?: string;
  allowances?: string;
  attendanceBonusThreshold?: string;
  attendanceBonusRate?: string;
  effectiveSalaryDate?: string;
  address?: string;
  city?: string;
  country?: string;
  emergencyContactName?: string;
  emergencyContactPhone?: string;
  manager?: string;
  workLocation?: string;
};
