ALTER TABLE "User"
ADD COLUMN "attendanceBonusRate" DECIMAL(5, 2) DEFAULT 5;

ALTER TABLE "PayrollRecord"
ADD COLUMN "expectedWorkHours" DECIMAL(8, 2) NOT NULL DEFAULT 0,
ADD COLUMN "workedHours" DECIMAL(8, 2) NOT NULL DEFAULT 0,
ADD COLUMN "overtimeHours" DECIMAL(8, 2) NOT NULL DEFAULT 0,
ADD COLUMN "shortHours" DECIMAL(8, 2) NOT NULL DEFAULT 0,
ADD COLUMN "overtimeAmount" DECIMAL(12, 2) NOT NULL DEFAULT 0,
ADD COLUMN "deductionAmount" DECIMAL(12, 2) NOT NULL DEFAULT 0;
